package main

import (
	"fmt"
	"github.com/jackc/pgx"
	"github.com/pringleskate/TP_DB_homework/internal/models"
	"github.com/pringleskate/TP_DB_homework/internal/storages/forumStorage"
	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
)

func main() {
	/*e := echo.New()

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.Logger.Fatal(e.Start(":1323"))*/

	connectionString := "postgres://postgres:qwerty1221@localhost/forumService?sslmode=disable"
	config, err := pgx.ParseURI(connectionString)
	if err != nil {
		fmt.Println(err)
		return
	}

	db, err := pgx.NewConnPool(
		pgx.ConnPoolConfig{
			ConnConfig:     config,
			MaxConnections: 10,
		})

	if err != nil {
		fmt.Println(err)
		return
	}


	//user := userStorage.NewStorage(db)
	forum := forumStorage.NewStorage(db)
	/*err = user.CreateUser(models.User{
		Nickname: "nick",
		Fullname: "kate",
		Email:    "pridius",
		About:    "",
	})*/

	created, err := forum.CreateForum(models.ForumCreate{
		Slug:  "lalala",
		Title: "title",
		User:  "nick",
	})
	fmt.Println(err, created)
}



